const responseEnum = {
  Success: "S",
  Error: "E",
  Saved: "Saved successfully",
  fetched: "Data Fetched successfully",
  Created: "Created successfully",
  Updated: "Updated successfully",
  Deleted: "Deleted successfully",
  Activated: "Activated successfully",
  Suspended: "Suspended successfully",
  Void: "Voided successfully",
  NotFound: "Not found",
  Approved: "Approved successfully",
  DataNotFound: "Data Not Found",
  NotCreated: "Not Created successfully",
  Disconnected: "Database Disconnected",
  Duplicate: "Duplicate Record",
  SignUp: "SignUp Completed Successfully",
  Login: "Login Successfully",
  InvalidEmail: "Please Enter Valid Email Address",
  Password: "Please Enter Valid Password",
  Verification: "Please Wait Your Account Under Verification",
  Locked: "Please Contact Admin Your Account Has been Locked",
  RateLimit: "Too many requests from this IP, please try again later",
  Documents: "Please upload the required documents",
  Files: "Please Enter the Valid fileTypes",
  NotRejected: "User Not In Rejected State",
  AboutUs: "Already about us registered. Please update if necessary",
  partnerAbout: "User is not a partner",
  Forbidden: "You do not have permission to access this resource",
  incorrectPasswordToken: "Password reset token is invalid or has expired",
  passwordMatch: "New password and confirm password do not match",
  passwordUpdated: "Password has been reset successfully",
  passwordToken: "password reset token has been sent to your mail successfully",
  productNotRegistered: "product not register yet",
  Unauthorized: "Your request appears to be unauthorized",
  AccessDenied: "Access denied. Please provide a valid access token",
  ContractDocumentUpdated: "Contract document Updated SuccessFully",
  ContractDocumentVerifiCation:
    "Your Contract documents under verification please wait while",
  ProductNotFound: "product not found",
  productDraft: "Product draft saved successfully",
  ProductDraftUpdated: "product draft updated successfully",
  InvalidParams: "Invalid params",
  ConnectAdmin: "please connect with admin you cant login for now",
  ConflictEmail:
    "please onboard another emailId already have an account for this email",
  ConflictMobile:
    "please onboard another mobile number already have an account for this mobile number",
};

module.exports = { responseEnum };
